name: Deploy Argo CD and Application

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'argocd')
    name: Deploy Argo CD and Application using Helm and Argo CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: code-review-platform-flow
          install_components: kubectl

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Argo CD Helm repository
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Deploy Argo CD
        run: |
          helm install argocd argo/argo-cd --namespace argocd --create-namespace

      - name: Get Argo CD admin password
        id: get_admin_password
        run: |
          kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode > admin-password.txt

      - name: Print Argo CD admin password
        run: cat admin-password.txt

      - name: Apply Argo CD Application
        run: kubectl apply -f applications/argocd-app.yaml
