name: Deploy Nginx to Kubernetes

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: code-review-platform-flow
          install_components: kubectl

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials primary --zone asia-northeast3-a --project code-review-platform-flow

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./applications/nginx/nginx-deployment.yaml
