name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Checkout tfvars repository
        uses: actions/checkout@v4.1.7
        with:
          repository: code-review-platform-flow/flow-terraform-tfvars
          token: ${{ secrets.GH_PAT }}
          path: tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.9.2

      - name: Configure GCP Credentials
        run: |
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" > ./gcp-key.json

      - name: Terraform Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp-key.json
        run: terraform init

      - name: Terraform Plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp-key.json
        run: terraform plan -var-file=tfvars/terraform.tfvars -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp-key.json
        run: terraform apply -auto-approve tfplan
